In [1]:
import pandas as pd
df = pd.read_excel("stocks.xlsx",header=[0,1])
df

  Unnamed: 0_level_0    Price                  Price to earnings ratio (P/E)  \
             Company Facebook Google Microsoft                      Facebook
0         2017-06-05      155    955        66                         37.10
1         2017-06-06      150    987        69                         36.98
2         2017-06-07      153    963        62                         36.78
3         2017-06-08      155   1000        61                         36.11
4         2017-06-09      156   1012        66                         37.07


  Google Microsoft
0   32.0     30.31
1   31.3     30.56
2   31.7     30.46
3   31.2     30.11
4   30.0     31.00

In [2]:
import pandas as pd
df = pd.read_excel("stocks.xlsx")
df

,Unnamed: 0,Price,Unnamed: 2,Unnamed: 3,Price to earnings ratio (P/E),Unnamed: 5,Unnamed: 6
0,Company,Facebook,Google,Microsoft,Facebook,Google,Microsoft
1,2017-06-05 00:00:00,155,955,66,37.1,32,30.31
2,2017-06-06 00:00:00,150,987,69,36.98,31.3,30.56
3,2017-06-07 00:00:00,153,963,62,36.78,31.7,30.46
4,2017-06-08 00:00:00,155,1000,61,36.11,31.2,30.11
5,2017-06-09 00:00:00,156,1012,66,37.07,30,31

In [3]:
import pandas as pd
df = pd.read_excel("stocks.xlsx",header=[0,1])
df

  Unnamed: 0_level_0    Price                  Price to earnings ratio (P/E)  \
             Company Facebook Google Microsoft                      Facebook
0         2017-06-05      155    955        66                         37.10
1         2017-06-06      150    987        69                         36.98
2         2017-06-07      153    963        62                         36.78
3         2017-06-08      155   1000        61                         36.11
4         2017-06-09      156   1012        66                         37.07


  Google Microsoft
0   32.0     30.31
1   31.3     30.56
2   31.7     30.46
3   31.2     30.11
4   30.0     31.00

In [4]:
df.stack()

C:\Users\S7061\AppData\Local\Temp\ipykernel_18220\3977694045.py:1: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  df.stack()

            Unnamed: 0_level_0   Price  Price to earnings ratio (P/E)
0 Company           2017-06-05     NaN                            NaN
  Facebook                 NaT   155.0                          37.10
  Google                   NaT   955.0                          32.00
  Microsoft                NaT    66.0                          30.31
1 Company           2017-06-06     NaN                            NaN
  Facebook                 NaT   150.0                          36.98
  Google                   NaT   987.0                          31.30
  Microsoft                NaT    69.0                          30.56
2 Company           2017-06-07     NaN                            NaN
  Facebook                 NaT   153.0                          36.78
  Google                   NaT   963.0                          31.70
  Microsoft                NaT    62.0                          30.46
3 Company           2017-06-08     NaN                            NaN
  Facebook                 NaT   155.0                          36.11
  Google                   NaT  1000.0                          31.20
  Microsoft                NaT    61.0                          30.11
4 Company           2017-06-09     NaN                            NaN
  Facebook                 NaT   156.0                          37.07
  Google                   NaT  1012.0                          30.00
  Microsoft                NaT    66.0                          31.00

In [5]:
df2 = pd.read_excel("stocks_3_levels.xlsx",header=[0,1,2])
df2

  Unnamed: 0_level_0 Price Ratios                   \
  Unnamed: 0_level_1        Price
             Company     Facebook Google Microsoft
0            Q1 2016          155    955        66
1            Q2 2016          150    987        69
2            Q3 2016          153    963        62
3            Q4 2016          155   1000        61
4            Q1 2017          156   1012        66

                                                 Income Statement         \
  Price to earnings ratio (P/E)                         Net Sales
                       Facebook Google Microsoft         Facebook Google
0                         37.10   32.0     30.31              2.6     20
1                         36.98   31.3     30.56              3.1     22
2                         36.78   31.7     30.46              4.3     24
3                         36.11   31.2     30.11              6.7     26
4                         37.07   30.0     31.00              8.1     31


            Net Profit
  Microsoft   Facebook Google Microsoft
0     18.70       0.80   5.43      4.56
1     21.30       0.97   5.89      5.10
2     21.45       1.20   6.10      5.43
3     21.88       1.67   6.50      5.89
4     22.34       2.03   6.40      6.09

In [6]:
df2.stack()

C:\Users\S7061\AppData\Local\Temp\ipykernel_18220\406340214.py:1: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  df2.stack()

            Unnamed: 0_level_0 Price Ratios                                \
            Unnamed: 0_level_1        Price Price to earnings ratio (P/E)
0 Company              Q1 2016          NaN                           NaN
  Facebook                 NaN        155.0                         37.10
  Google                   NaN        955.0                         32.00
  Microsoft                NaN         66.0                         30.31
1 Company              Q2 2016          NaN                           NaN
  Facebook                 NaN        150.0                         36.98
  Google                   NaN        987.0                         31.30
  Microsoft                NaN         69.0                         30.56
2 Company              Q3 2016          NaN                           NaN
  Facebook                 NaN        153.0                         36.78
  Google                   NaN        963.0                         31.70
  Microsoft                NaN         62.0                         30.46
3 Company              Q4 2016          NaN                           NaN
  Facebook                 NaN        155.0                         36.11
  Google                   NaN       1000.0                         31.20
  Microsoft                NaN         61.0                         30.11
4 Company              Q1 2017          NaN                           NaN
  Facebook                 NaN        156.0                         37.07
  Google                   NaN       1012.0                         30.00
  Microsoft                NaN         66.0                         31.00

            Income Statement
                   Net Sales Net Profit
0 Company                NaN        NaN
  Facebook              2.60       0.80
  Google               20.00       5.43
  Microsoft            18.70       4.56
1 Company                NaN        NaN
  Facebook              3.10       0.97
  Google               22.00       5.89
  Microsoft            21.30       5.10
2 Company                NaN        NaN
  Facebook              4.30       1.20
  Google               24.00       6.10
  Microsoft            21.45       5.43
3 Company                NaN        NaN
  Facebook              6.70       1.67
  Google               26.00       6.50
  Microsoft            21.88       5.89
4 Company                NaN        NaN
  Facebook              8.10       2.03
  Google               31.00       6.40
  Microsoft            22.34       6.09

In [7]:
pd.crosstab(df.Nationality,df.Handedness)

AttributeError: 'DataFrame' object has no attribute 'Nationality'